name: lemp
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php8:
    container_name: php8
    build:
      context: .
      dockerfile: php/php8.Dockerfile
    volumes:
        - ./www:/var/www/html
        - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini

  php74:
    container_name: php74
    build:
      context: .
      dockerfile: php/php74.Dockerfile
    volumes:
        - ./www:/var/www/html
        - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini

  mysql:
    container_name: mysql
    image: mysql:latest
    command: --mysql_native_password=ON
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

  pma:
    container_name: pma
    image: phpmyadmin:latest
    environment:
      - PMA_HOST=mysql        
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_PORT=3306
    ports:
      - 8888:80